# Generated by Django 6.0.3 on 2026-03-04 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Missed', 'Missed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('id_number', models.CharField(max_length=20, unique=True)),
                ('date_of_birth', models.DateField()),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('expected_delivery_date', models.DateField()),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('gestational_age_weeks', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Attended', 'Attended'), ('Missed', 'Missed')], max_length=10)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='clinic.appointment')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='clinic.patient'),
        ),
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('message_content', models.TextField()),
                ('status', models.CharField(choices=[('Sent', 'Sent'), ('Failed', 'Failed')], max_length=10)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_logs', to='clinic.appointment')),
            ],
        ),
    ]
